# See https://ezcv.readthedocs.io for documentation
name: Yeet
theme: turing
resume: false
biography: A description of yourself # This field is for writing about yourself you can add a > to span multiple lines
